/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/src/Route`; params?: Router.UnknownInputParams; } | { pathname: `/src/Store`; params?: Router.UnknownInputParams; } | { pathname: `/src/actions/HomeAction`; params?: Router.UnknownInputParams; } | { pathname: `/src/actions/Types`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/AddUpdateTask`; params?: Router.UnknownInputParams; } | { pathname: `/src/reducers/HomeReducer`; params?: Router.UnknownInputParams; } | { pathname: `/src/reducers`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/Details`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/Home`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/Login`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/Signup`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/Splash`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/URL`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/services`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/src/Route`; params?: Router.UnknownOutputParams; } | { pathname: `/src/Store`; params?: Router.UnknownOutputParams; } | { pathname: `/src/actions/HomeAction`; params?: Router.UnknownOutputParams; } | { pathname: `/src/actions/Types`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/AddUpdateTask`; params?: Router.UnknownOutputParams; } | { pathname: `/src/reducers/HomeReducer`; params?: Router.UnknownOutputParams; } | { pathname: `/src/reducers`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/Details`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/Signup`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/Splash`; params?: Router.UnknownOutputParams; } | { pathname: `/src/utils/URL`; params?: Router.UnknownOutputParams; } | { pathname: `/src/utils/services`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/src/Route${`?${string}` | `#${string}` | ''}` | `/src/Store${`?${string}` | `#${string}` | ''}` | `/src/actions/HomeAction${`?${string}` | `#${string}` | ''}` | `/src/actions/Types${`?${string}` | `#${string}` | ''}` | `/src/components/AddUpdateTask${`?${string}` | `#${string}` | ''}` | `/src/reducers/HomeReducer${`?${string}` | `#${string}` | ''}` | `/src/reducers${`?${string}` | `#${string}` | ''}` | `/src/screens/Details${`?${string}` | `#${string}` | ''}` | `/src/screens/Home${`?${string}` | `#${string}` | ''}` | `/src/screens/Login${`?${string}` | `#${string}` | ''}` | `/src/screens/Signup${`?${string}` | `#${string}` | ''}` | `/src/screens/Splash${`?${string}` | `#${string}` | ''}` | `/src/utils/URL${`?${string}` | `#${string}` | ''}` | `/src/utils/services${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/src/Route`; params?: Router.UnknownInputParams; } | { pathname: `/src/Store`; params?: Router.UnknownInputParams; } | { pathname: `/src/actions/HomeAction`; params?: Router.UnknownInputParams; } | { pathname: `/src/actions/Types`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/AddUpdateTask`; params?: Router.UnknownInputParams; } | { pathname: `/src/reducers/HomeReducer`; params?: Router.UnknownInputParams; } | { pathname: `/src/reducers`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/Details`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/Home`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/Login`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/Signup`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/Splash`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/URL`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/services`; params?: Router.UnknownInputParams; };
    }
  }
}
